# Generated by Django 4.1.3 on 2022-12-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='solve_count',
            field=models.SmallIntegerField(default=0),
        ),
    ]
