# Generated by Django 4.1.3 on 2022-12-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_solve_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='임시닉네임', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='sock_image_url1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sock_image_url2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sock_image_url3',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
