# Generated by Django 4.1.3 on 2022-12-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_nickname_user_sock_image_url1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='undefiend', max_length=100),
        ),
    ]
