# Generated by Django 4.1.3 on 2022-12-12 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sock_image_url1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sock_image_url2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sock_image_url3',
        ),
    ]
