# Generated by Django 4.1.3 on 2022-12-13 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_nickname'),
        ('accounts', '0004_alter_user_nickname'),
    ]

    operations = [
    ]
