# Generated by Django 4.1.3 on 2022-12-14 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20221213_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sock_image_url1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sock_image_url2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sock_image_url3',
        ),
    ]
