# Generated by Django 4.1.3 on 2022-12-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sock',
            name='sock1_img',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='sock',
            name='sock1_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='sock',
            name='sock2_img',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='sock',
            name='sock2_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='sock',
            name='sock3_img',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='sock',
            name='sock3_name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
