# Generated by Django 4.1.3 on 2022-12-08 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealWreath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orn1', models.SmallIntegerField()),
                ('orn2', models.SmallIntegerField()),
                ('orn3', models.SmallIntegerField()),
                ('orn4', models.SmallIntegerField()),
                ('orn5', models.SmallIntegerField()),
                ('orn6', models.SmallIntegerField()),
                ('orn7', models.SmallIntegerField()),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_RealWreath', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
