# Generated by Django 4.1.3 on 2022-11-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_quiz_answer_quiz_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='body_color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deco', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='body_eco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deco', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='deer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horn', models.CharField(max_length=200)),
                ('hair', models.CharField(max_length=200)),
                ('eye', models.CharField(max_length=200)),
                ('body_color', models.CharField(max_length=200)),
                ('body_eco', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='eye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deco', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='hair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deco', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='horn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deco', models.CharField(max_length=200)),
            ],
        ),
    ]
