# Generated by Django 4.1.3 on 2022-11-23 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0003_body_color_body_eco_deer_eye_hair_horn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='body_eco',
            new_name='body_deco',
        ),
        migrations.DeleteModel(
            name='deer',
        ),
    ]
