# Generated by Django 4.1.3 on 2022-12-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0003_alter_realwreath_orn1_alter_realwreath_orn2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deer',
            old_name='body_color',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='deer',
            old_name='body_deco',
            new_name='bodydeco',
        ),
        migrations.RenameField(
            model_name='deer',
            old_name='hair',
            new_name='headdeco',
        ),
    ]
