# Generated by Django 4.1.3 on 2022-12-12 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wall', '0004_ornamentlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sock1_name', models.CharField(default=-1, max_length=200)),
                ('sock1_img', models.CharField(default=-1, max_length=200)),
                ('sock2_name', models.CharField(default=-1, max_length=200)),
                ('sock2_img', models.CharField(default=-1, max_length=200)),
                ('sock3_name', models.CharField(default=-1, max_length=200)),
                ('sock3_img', models.CharField(default=-1, max_length=200)),
                ('user_id', models.ForeignKey(db_column='u_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_sock', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
