# Generated by Django 4.1.3 on 2022-12-07 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wall', '0005_deer_mixdeer_delete_body_color_delete_body_deco_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mixdeer',
            old_name='body_color',
            new_name='m_body_color',
        ),
        migrations.RenameField(
            model_name='mixdeer',
            old_name='body_deco',
            new_name='m_body_deco',
        ),
        migrations.RenameField(
            model_name='mixdeer',
            old_name='eye',
            new_name='m_eye',
        ),
        migrations.RenameField(
            model_name='mixdeer',
            old_name='hair',
            new_name='m_hair',
        ),
        migrations.RenameField(
            model_name='mixdeer',
            old_name='horn',
            new_name='m_horn',
        ),
        migrations.AddField(
            model_name='mixdeer',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_deer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='wreath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=200)),
                ('width', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_wreath', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
