# Generated by Django 4.1.3 on 2022-12-13 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0005_sock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='quiz',
        ),
        migrations.DeleteModel(
            name='user_A',
        ),
    ]
