# Generated by Django 4.1.3 on 2022-12-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0005_sock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deer',
            old_name='body',
            new_name='body_color',
        ),
        migrations.RenameField(
            model_name='deer',
            old_name='bodydeco',
            new_name='body_deco',
        ),
        migrations.RenameField(
            model_name='deer',
            old_name='headdeco',
            new_name='hair',
        ),
        migrations.RenameField(
            model_name='sock',
            old_name='u_id',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='sock',
            name='sock1_img',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sock',
            name='sock1_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sock',
            name='sock2_img',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sock',
            name='sock2_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sock',
            name='sock3_img',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sock',
            name='sock3_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
