# Generated by Django 4.1.3 on 2022-12-13 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0006_delete_quiz_delete_user_a'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wreath',
        ),
    ]
