# Generated by Django 4.1.3 on 2022-11-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0006_rename_body_color_mixdeer_m_body_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50)),
            ],
        ),
    ]
