# Generated by Django 4.1.3 on 2022-12-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0007_user_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='wreath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.CharField(max_length=200)),
                ('src', models.CharField(max_length=200)),
            ],
        ),
    ]
